package TrainComposition.TrainCars.Abstract;

public enum TrainCarTypes {
    PASSENGER_CAR,
    RESTAURANT_CAR,
    BAGGAGE_MAIL_CAR,
    GASEOUS_MATERIALS_CAR,
    LIQUID_GOODS_CAR,
    MAIL_CAR,
    REFRIGERATED_CAR,
    EXPLOSIVES_CAR,
    LIQUID_TOXIC_MATERIALS_CAR,
    TOXIC_MATERIALS_CAR,
}
